package attest

import (
	"bytes"
	"crypto/rand"
	"errors"
	"fmt"
	"io"

	"github.com/loicsikidi/attest/endorsement"
	"github.com/loicsikidi/go-tpm-kit/tpmcrypto"

	"github.com/google/go-tpm/tpm2"
)

const (
	// activationSecretLen is the size in bytes of the generated secret
	// which is generated for credential activation.
	activationSecretLen = 32
)

// ActivationParameters encapsulates the inputs for activating an AK.
type ActivationParameters struct {
	// EK, the endorsement key, describes an asymmetric key whose
	// private key is permanently bound to the TPM.
	//
	// Activation will verify that the provided EK is held on the same
	// TPM as the AK. However, it is the caller's responsibility to
	// ensure the EK they provide corresponds to the the device which
	// they are trying to associate the AK with.
	//
	// Note; LabeledEncapsulationKey interface is a representation of a public key
	EK tpm2.LabeledEncapsulationKey

	// AK, the Attestation Key, describes the properties of
	// an asymmetric key (managed by the TPM) which signs attestation
	// structures.
	// The values from this structure can be obtained by calling
	// Parameters() on an attest.AK.
	AK AttestationParameters

	// Rand is a source of randomness to generate a seed and secret for the
	// challenge.
	//
	// If nil, this defaults to tpmcrypto.Rand.
	Rand io.Reader
}

func NewActivationParameters(ek endorsement.EK, ak AttestationParameters) (*ActivationParameters, error) {
	key, err := tpm2.ImportEncapsulationKey(ek.Public)
	if err != nil {
		return nil, fmt.Errorf("import encapsulation key: %w", err)
	}
	return &ActivationParameters{
		EK:   key,
		AK:   ak,
		Rand: rand.Reader,
	}, nil
}

// CheckAKParameters examines properties of an AK and a creation
// attestation, to determine if it is suitable for use as an attestation key.
func (p *ActivationParameters) CheckAKParameters() error {
	var (
		att   = p.AK.CreateAttestation
		akPub = p.AK.Public
	)
	if att.Type != tpm2.TPMSTAttestCreation {
		return fmt.Errorf("attestation does not apply to creation data, got tag %#x", att.Type)
	}

	if err := tpmcrypto.ValidatePublicKey(*p.AK.Public); err != nil {
		return fmt.Errorf("validate public key: %w", err)
	}

	// Compute & verify that the creation data matches the digest in the
	// attestation structure.
	nameHash, err := akPub.NameAlg.Hash()
	if err != nil {
		return fmt.Errorf("get name hash: %w", err)
	}
	createDataDigest, err := tpmcrypto.GetDigest(tpm2.Marshal(p.AK.CreateData), nameHash)
	if err != nil {
		return fmt.Errorf("get digest: %w", err)
	}

	creationInfo, err := att.Attested.Creation()
	if err != nil {
		return fmt.Errorf("get creation info: %w", err)
	}
	if !bytes.Equal(creationInfo.CreationHash.Buffer, createDataDigest) {
		return errors.New("attestation refers to different public key")
	}

	// Make sure the AK has sane key parameters (Attestation can be faked if an AK
	// can be used for arbitrary signatures).
	// We verify the following:
	// - Key is TPM backed.
	// - Key is TPM generated.
	// - Key is a restricted key (means it cannot do arbitrary signing/decrypt ops).
	// - Key cannot be duplicated.
	// - Key was generated by a call to TPM_Create*.
	if err := att.Magic.Check(); err != nil {
		return errors.New("creation attestation was not produced by a TPM")
	}
	if !akPub.ObjectAttributes.FixedTPM {
		return errors.New("AK is exportable")
	}
	if !akPub.ObjectAttributes.Restricted || !akPub.ObjectAttributes.FixedParent || !akPub.ObjectAttributes.SensitiveDataOrigin {
		return errors.New("provided key is not limited to attestation")
	}

	// Verify the attested creation name matches what is computed from
	// the public key.
	akPubName, err := tpm2.ObjectName(akPub)
	if err != nil {
		return fmt.Errorf("get object name: %w", err)
	}

	if !bytes.Equal(creationInfo.ObjectName.Buffer, akPubName.Buffer) {
		return errors.New("certification refers to a different key")
	}

	// Check the signature over the attestation data verifies correctly.
	return tpmcrypto.VerifySignatureFromPublic(*akPub, p.AK.CreateSignature, tpm2.Marshal(p.AK.CreateAttestation))
}

// Generate returns a credential activation challenge, which can be provided
// to the TPM to verify the AK parameters given are authentic & the AK
// is present on the same TPM as the EK.
//
// It will call CheckAKParameters() at the beginning and return the error if
// there is any.
//
// The caller is expected to verify the secret returned from the TPM as
// as result of calling ActivateCredential() matches the secret returned here.
// The caller should use subtle.ConstantTimeCompare to avoid potential
// timing attack vectors.
func (p *ActivationParameters) Generate() (secret []byte, ec *EncryptedCredential, err error) {
	if err := p.CheckAKParameters(); err != nil {
		return nil, nil, err
	}

	if p.EK == nil {
		return nil, nil, errors.New("no EK provided")
	}

	if p.Rand == nil {
		p.Rand = rand.Reader
	}

	rnd, secret := p.Rand, make([]byte, activationSecretLen)
	if _, err = io.ReadFull(rnd, secret); err != nil {
		return nil, nil, fmt.Errorf("failed to generate activation secret: %w", err)
	}

	ec, err = p.generateChallenge(secret)
	if err != nil {
		return nil, nil, fmt.Errorf("generate challenge: %w", err)
	}
	return secret, ec, nil
}

func (p *ActivationParameters) generateChallenge(secret []byte) (*EncryptedCredential, error) {
	att := p.AK.CreateAttestation

	if att.Type != tpm2.TPMSTAttestCreation {
		return nil, errors.New("attestation was not for a creation event")
	}

	creationInfo, err := att.Attested.Creation()
	if err != nil {
		return nil, fmt.Errorf("get creation info: %w", err)
	}

	if creationInfo.ObjectName.Buffer == nil {
		return nil, errors.New("attestation creation info name has no digest")
	}

	cred, encSecret, err := tpm2.CreateCredential(p.Rand, p.EK, creationInfo.ObjectName.Buffer, secret)
	if err != nil {
		return nil, fmt.Errorf("create credential: %w", err)
	}

	return &EncryptedCredential{
		Credential: cred,
		Secret:     encSecret,
	}, nil
}
