// Copyright 2019 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This file has been modified by lsikidi.
package attest

import (
	"github.com/loicsikidi/attest/endorsement"
	"github.com/loicsikidi/attest/info"
	"github.com/loicsikidi/attest/kty"
	"github.com/loicsikidi/go-tpm-kit/tpmutil"

	"github.com/google/go-tpm/tpm2"
)

const (
	tpmRoot = "/sys/class/tpm"
)

type tpmBase interface {
	close() error
	eks() ([]endorsement.EK, error)
	ekCertificates(optionalCfg ...SearchEKCertConfig) ([]endorsement.EK, error)
	info() (*info.TPMInfo, error)
	pcrbanks() ([]tpm2.TPMIAlgHash, error)
	// pcrs(bank pcr.Bank) ([]pcr.PCR, error)
	// measurementLog() ([]byte, error)

	loadAK(opaqueBlob []byte) (*AK, error)
	loadAKWithParent(opaqueBlob []byte, parent ParentKeyConfig) (*AK, error)
	newAK(opts *AKConfig) (*AK, error)
	loadKeyWithParent(opaqueBlob []byte, parent ParentKeyConfig) (*Key, error)
	loadKey(opaqueBlob []byte) (*Key, error)
	newKey(ak *AK, opts *KeyConfig) (*Key, error)
	newKeyCertifiedByKey(ck certifyingKey, opts *KeyConfig) (*Key, error)
}

// TPM struct with a TPM device on the system.
type TPM struct {
	tpm tpmBase
}

// Close shuts down the connection to the TPM.
func (t *TPM) Close() error {
	return t.tpm.close()
}

// EKs returns the endorsement keys burned-in to the platform.
// If no certificates are found, the function will fall back
// to RSA 2048 (low-range) EK without certificate.
//
// Note: for the moment, we keep upstream behavior
func (t *TPM) EKs() ([]endorsement.EK, error) {
	return t.tpm.eks()
}

// EKCertificates returns the endorsement key certificates burned-in to the platform.
// It is guaranteed that each EK.Certificate field will be populated.
func (t *TPM) EKCertificates(optionalCfg ...SearchEKCertConfig) ([]endorsement.EK, error) {
	return t.tpm.ekCertificates(optionalCfg...)
}

// NewAK creates an attestation key.
func (t *TPM) NewAK(opts *AKConfig) (*AK, error) {
	return t.tpm.newAK(opts)
}

// Info retrieves static information about the TPM.
func (t *TPM) Info() (*info.TPMInfo, error) {
	return t.tpm.info()
}

// LoadAK loads a previously-created ak into the TPM for use.
// A key loaded via this function needs to be closed with .Close().
// Only blobs generated by calling AK.Marshal() are valid parameters
// to this function.
func (t *TPM) LoadAK(opaqueBlob []byte) (*AK, error) {
	return t.tpm.loadAK(opaqueBlob)
}

// LoadAKWithParent loads a previously-created ak into the TPM
// under the given parent for use.
func (t *TPM) LoadAKWithParent(opaqueBlob []byte, parent ParentKeyConfig) (*AK, error) {
	return t.tpm.loadAKWithParent(opaqueBlob, parent)
}

// PCRBanks returns the list of supported PCR banks on the TPM.
//
// This is a low-level API. Consumers seeking to attest the state of the
// platform should use tpm.AttestPlatform() instead.
func (t *TPM) PCRBanks() ([]tpm2.TPMIAlgHash, error) {
	return t.tpm.pcrbanks()
}

// NewKey creates an application key certified by the attestation key. If opts is nil
// then DefaultConfig is used.
func (t *TPM) NewKey(ak *AK, opts *KeyConfig) (*Key, error) {
	if opts == nil {
		opts = defaultConfig
	}
	if opts.KeyType == 0 {
		opts = defaultConfig
	}
	return t.tpm.newKey(ak, opts)
}

// LoadKey loads a previously-created application key into the TPM for use.
// A key loaded via this function needs to be closed with .Close().
// Only blobs generated by calling Key.Marshal() are valid parameters
// to this function.
func (t *TPM) LoadKey(opaqueBlob []byte) (*Key, error) {
	return t.tpm.loadKey(opaqueBlob)
}

// NewKeyCertifiedByKey creates an application key certified by
// the attestation key. Unlike NewKey(), this method does not require
// an attest.AK object and only requires the AK handle and its algorithm.
// Thus it can be used in cases where the attestation key was not created
// by go-attestation library. If opts is nil then DefaultConfig is used.
func (t *TPM) NewKeyCertifiedByKey(akHandle any, akType kty.KeyType, opts *KeyConfig) (*Key, error) {
	if opts == nil {
		opts = defaultConfig
	}
	if opts.KeyType == 0 {
		opts = defaultConfig
	}

	handle, err := tpmutil.ToHandle(t.tpm.(*tpmbase).rwc, akHandle)
	if err != nil {
		return nil, err
	}
	ck := certifyingKey{handle: handle, keyType: akType}
	return t.tpm.newKeyCertifiedByKey(ck, opts)
}
